#Created by Shashwat Raj
#Program to generate mad libs game
Animal=input("Enter an animal: ")
Feeling=input("Enter a feeling: ")
Things=input("Input any things (plural): ")
Professional=input("Enter a profession (ex-Doctor): ")
Cloth=input("Enter a piece of clothing: ")
Things2=input("Input any things (plural): ")
A_person=input("Enter a person: ")
Place=input("Enter a place: ")
Verb=input("Enter a verb (with ing): ")
Food=input("Enter a food: ")
print("Say '"+Food+"' the photographer said as the camera flashed!")
print(A_person + " and I had gone to " + Place +" to get our photos taken today.")
print("The first photo we really wanted was a picture of us dressed as "+ Animal +" pretending to be a " + Professional)
print("When we saw the proofs of it, I was a bit " + Feeling + " because it looked different than in my head.")
print("(I hadn't imagined so many " + Things + " behind us.)")
print("However, the second photo was exactly what I wanted.")
print("We both looked like " +Things2 + " wearing " + Cloth + " and " + Verb + " --exactly what I had in mind!")
